export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const NOTIFICATIONS_LOADING = "NOTIFICATIONS_LOADING";
export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
