export const GET_PROGRAMS = "GET_PROGRAMS";
export const GET_PROGRAM = "GET_PROGRAM";
export const CREATE_PROGRAM = "CREATE_PROGRAM";
export const UPDATE_PROGRAM = "UPDATE_PROGRAM";
export const DELETE_PROGRAM = "DELETE_PROGRAM";
export const PROGRAMS_LOADING = "PROGRAMS_LOADING";
