export const GET_SETTINGS = "GET_SETTINGS";
export const SETTINGS_LOADING = "SETTINGS_LOADING";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";

// System settings
export const GET_SYSTEM_SETTINGS = "GET_SYSTEM_SETTINGS";
export const SYSTEM_SETTINGS_LOADING = "SYSTEM_SETTINGS_LOADING";
export const UPDATE_SYSTEM_SETTINGS = "UPDATE_SYSTEM_SETTINGS";
