export const GET_WAREHOUSES = "GET_WAREHOUSES";
export const GET_WAREHOUSE = "GET_WAREHOUSE";
export const CREATE_WAREHOUSE = "CREATE_WAREHOUSE";
export const UPDATE_WAREHOUSE = "UPDATE_WAREHOUSE";
export const DELETE_WAREHOUSE = "DELETE_WAREHOUSE";
export const WAREHOUSES_LOADING = "WAREHOUSES_LOADING";
